name: Docker

on:
  push:
    branches: [development]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (Docker Hub)
        if: ${{ github.event_name != 'schedule' }}
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag denizugur/mmsys21cheapfakes:submission \
            --file ./Dockerfile ./

      - name: Inspect image (Docker Hub)
        run: |
          docker buildx imagetools inspect denizugur/mmsys21cheapfakes:submission

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx (GitHub Container Registry)
        if: ${{ github.event_name != 'schedule' }}
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag ghcr.io/denizugur/mmsys21cheapfakes:submission \
            --file ./Dockerfile ./
